INSERT INTO sports (sport, sport_code, sport_URL) VALUES
('Archery','ARC','https://olympics.com/en/paris-2024/sports/archery') ,
('Artistic Gymnastics','GAR','https://olympics.com/en/paris-2024/sports/artistic-gymnastics') ,
('Artistic Swimming','SWA','https://olympics.com/en/paris-2024/sports/artistic-swimming') ,
('Athletics','ATH','https://olympics.com/en/paris-2024/sports/athletics') ,
('Badminton','BDM','https://olympics.com/en/paris-2024/sports/badminton') ,
('Basketball','BKB','https://olympics.com/en/paris-2024/sports/basketball') ,
('3x3 Basketball','BK3','https://olympics.com/en/paris-2024/sports/3x3-basketball') ,
('Beach Volleyball','VBV','https://olympics.com/en/paris-2024/sports/beach-volleyball') ,
('Boxing','BOX','https://olympics.com/en/paris-2024/sports/boxing') ,
('Breaking','BKG','https://olympics.com/en/paris-2024/sports/breaking') ,
('Canoe Slalom','CSL','https://olympics.com/en/paris-2024/sports/canoe-kayak-slalom') ,
('Canoe Sprint','CSP','https://olympics.com/en/paris-2024/sports/canoe-kayak-flatwater') ,
('Cycling BMX Freestyle','BMF','https://olympics.com/en/paris-2024/sports/cycling-bmx-freestyle') ,
('Cycling BMX Racing','BMX','https://olympics.com/en/paris-2024/sports/cycling-bmx-racing') ,
('Cycling Mountain Bike','MTB','https://olympics.com/en/paris-2024/sports/cycling-mountain-bike') ,
('Cycling Road','CRD','https://olympics.com/en/paris-2024/sports/cycling-road') ,
('Cycling Track','CTR','https://olympics.com/en/paris-2024/sports/cycling-track') ,
('Diving','DIV','https://olympics.com/en/paris-2024/sports/diving') ,
('Equestrian','EQU','https://olympics.com/en/paris-2024/sports/equestrian') ,
('Fencing','FEN','https://olympics.com/en/paris-2024/sports/fencing') ,
('Football','FBL','https://olympics.com/en/paris-2024/sports/football') ,
('Golf','GLF','https://olympics.com/en/paris-2024/sports/golf') ,
('Handball','HBL','https://olympics.com/en/paris-2024/sports/handball') ,
('Hockey','HOC','https://olympics.com/en/paris-2024/sports/hockey') ,
('Judo','JUD','https://olympics.com/en/paris-2024/sports/judo') ,
('Marathon Swimming','OWS','https://olympics.com/en/paris-2024/sports/marathon-swimming') ,
('Modern Pentathlon','MPN','https://olympics.com/en/paris-2024/sports/modern-pentathlon') ,
('Rhythmic Gymnastics','GRY','https://olympics.com/en/paris-2024/sports/rhythmic-gymnastics') ,
('Rowing','ROW','https://olympics.com/en/paris-2024/sports/rowing') ,
('Rugby Sevens','RU7','https://olympics.com/en/paris-2024/sports/rugby-sevens') ,
('Sailing','SAL','https://olympics.com/en/paris-2024/sports/sailing') ,
('Shooting','SHO','https://olympics.com/en/paris-2024/sports/shooting') ,
('Skateboarding','SKB','https://olympics.com/en/paris-2024/sports/skateboarding') ,
('Sport Climbing','CLB','https://olympics.com/en/paris-2024/sports/sport-climbing') ,
('Surfing','SRF','https://olympics.com/en/paris-2024/sports/surfing') ,
('Swimming','SWM','https://olympics.com/en/paris-2024/sports/swimming') ,
('Table Tennis','TTE','https://olympics.com/en/paris-2024/sports/table-tennis') ,
('Taekwondo','TKW','https://olympics.com/en/paris-2024/sports/taekwondo') ,
('Tennis','TEN','https://olympics.com/en/paris-2024/sports/tennis') ,
('Trampoline Gymnastics','GTR','https://olympics.com/en/paris-2024/sports/trampoline-gymnastics') ,
('Triathlon','TRI','https://olympics.com/en/paris-2024/sports/triathlon') ,
('Volleyball','VVO','https://olympics.com/en/paris-2024/sports/volleyball') ,
('Water Polo','WPO','https://olympics.com/en/paris-2024/sports/water-polo') ,
('Weightlifting','WLF','https://olympics.com/en/paris-2024/sports/weightlifting') ,
('Wrestling','WRE','https://olympics.com/en/paris-2024/sports/wrestling')